config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new', as: :new
  post 'score', to: 'games#score', as: :score
  get 'reset', to: 'games#reset'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require "open-uri"

class GamesController < ApplicationController
  VOWELS = %w(A E I O U Y)

  def new
    @letters = Array.new(5) { VOWELS.sample }
    @letters += Array.new(5) { (('A'..'Z').to_a - VOWELS).sample }
    @letters.shuffle!
  end

  def score
    session[:score] = 0 if session[:score].nil?
    @letters = params[:letters].split
    @word = (params[:word] || "").upcase
    @included = included?(@word, @letters)
    @english_word = english_word?(@word)
    @score = calculate_score
    session[:score] += @score
    @total_score = session[:score]
  end

  def reset
    reset_session
    redirect_to new_url
    session[:score] = 0
  end

  private

  def calculate_score
    if @included && @english_word
      @word.length
    else
      0
    end
  end

  def included?(word, letters)
    word.chars.all? { |letter| word.count(letter) <= letters.count(letter) }
    # .chars return un'array di letter = .split("")
    # .count(letter) returns the num of times a letter appears
    # .all? { |obj| block } => Passes each element of the collection to the given block. The method returns true
    # if the block never returns false or nil. In questo caso verifica che ogni lettera dell'attempt appare
    # lo stesso num di volte o meno che nella griglia
  end

  def english_word?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<ul class="letters">
  <% @letters.each do |letter| %>
    <li><%= letter %></li>
  <% end %>
</ul>

<p class="form-prefix">What is the longest word you can find?</p>

<form action="/score" method="POST" class="form-inline">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :letters, @letters %>
  <div class="input-group input-group">
    <input type="text" name="word" class="form-control" placeholder="Your word">
    <span class="input-group-btn">
      <input type="submit" value="Play" class="btn btn-primary">
     </span>
  </div>
</form>
<br>
<p class="score">Your score: <%= session[:score] %> <p class="btn btn-light"><%= link_to "Reset score", reset_path %></p>

app/views/games/score.html.erb
<h1>Result</h1>

<% if @included %>
  <% if @english_word %>
    <p><strong>Congratulations!</strong> <%= @word %> is a valid English word!<br>
      You scored <%= @score %> points this round</p>
  <% else %>
    <p>Sorry but <strong><%= @word %></strong> does not seem to be a valid English word...</p>
  <% end %>
<% else %>
  <p>Sorry but <strong><%= @word %></strong> can't be built out of <%= @letters.join(", ") %></p>
<% end %>

<p>Your score: <%= @total_score %></p>

<%= link_to "Play again", new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGameReboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>